# Generated by Django 6.0.6 on 2026-06-17 09:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20)),
                ('event_name', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('corporate', 'Corporate Event'), ('conference', 'Conference'), ('seminar', 'Seminar'), ('exhibition', 'Exhibition'), ('concert', 'Concert'), ('private', 'Private Function'), ('other', 'Other')], max_length=50)),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial Paid'), ('paid', 'Fully Paid')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('inquiry', 'Inquiry'), ('reserved', 'Reserved'), ('booked', 'Booked'), ('confirmed', 'Confirmed'), ('occupied', 'Occupied'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='inquiry', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('auditorium', 'Auditorium'), ('house', 'House'), ('villa', 'Villa'), ('resort', 'Resort'), ('plot', 'Plot'), ('commercial', 'Commercial Building')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('google_map_link', models.URLField(blank=True)),
                ('capacity', models.PositiveIntegerField()),
                ('rent_type', models.CharField(choices=[('hourly', 'Hourly'), ('half_day', 'Half Day'), ('full_day', 'Full Day')], max_length=20)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slot_type', models.CharField(choices=[('full_day', 'Full Day'), ('half_day_morning', 'Half Day (Morning)'), ('half_day_evening', 'Half Day (Evening)'), ('hourly_1', '1 Hour'), ('hourly_2', '2 Hours'), ('hourly_3', '3 Hours'), ('hourly_4', '4 Hours'), ('hourly_5', '5 Hours'), ('hourly_6', '6 Hours'), ('custom', 'Custom')], max_length=30)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=30)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='api.property'),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.property')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='api.slot'),
        ),
    ]
