# Generated by Django 6.0.6 on 2026-06-17 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rent_amount',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rent_type',
        ),
        migrations.AddField(
            model_name='booking',
            name='duration_hours',
            field=models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=4),
        ),
        migrations.CreateModel(
            name='PropertySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_type', models.CharField(choices=[('full_day', 'Full Day'), ('half_day', 'Half Day'), ('hourly', 'Hourly')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_duration_hours', models.DecimalField(decimal_places=1, default=1, max_digits=4)),
                ('max_duration_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='api.property')),
            ],
            options={
                'ordering': ['property', 'slot_type', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='property_slot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='api.propertyslot'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Slot',
        ),
    ]
