# Generated by Django 6.0.6 on 2026-06-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_booking_slot_remove_property_rent_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyslot',
            options={'ordering': ['property', 'slot_type']},
        ),
        migrations.RemoveField(
            model_name='propertyslot',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='propertyslot',
            name='label',
        ),
        migrations.RemoveField(
            model_name='propertyslot',
            name='start_time',
        ),
    ]
