# Generated by Django 5.2.15 on 2026-06-23 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_property_property_id_propertyslot_slot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='reserved', max_length=20),
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('event_name', models.CharField(blank=True, max_length=255)),
                ('event_type', models.CharField(blank=True, choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('corporate', 'Corporate Event'), ('conference', 'Conference'), ('seminar', 'Seminar'), ('exhibition', 'Exhibition'), ('concert', 'Concert'), ('private', 'Private Function'), ('other', 'Other')], max_length=50)),
                ('enquiry_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('enquiry', 'Enquiry'), ('reserved', 'Reserved')], default='enquiry', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiry', to='api.booking')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='api.client')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enquiries', to='api.property')),
                ('property_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enquiries', to='api.propertyslot')),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
